use std::fmt;

pub enum Estado {
    Aguascalientes,
    BajaCalifornia,
    BajaCaliforniaSur,
    Campeche,
    Coahuila,
    Colima,
    Chiapas,
    Chihuahua,
    DistritoFederal,
    Cdmx,
    Durango,
    Guanajuato,
    Guerrero,
    Hidalgo,
    Jalisco,
    EstadoDeMexico,
    Extranjero,
    Michoacan,
    Morelos,
    Nayarit,
    NuevoLeon,
    Oaxaca,
    Puebla,
    Queretaro,
    QuintanaRoo,
    SanLuisPotosi,
    Sinaloa,
    Sonora,
    Tabasco,
    Tamaulipas,
    Tlaxcala,
    Veracruz,
    Yucatan,
    Zacatecas,
}

impl fmt::Display for Estado {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Estado::Aguascalientes => write!(f, "AS"),
            Estado::BajaCalifornia => write!(f, "BC"),
            Estado::BajaCaliforniaSur => write!(f, "BS"),
            Estado::Campeche => write!(f, "CC"),
            Estado::Coahuila => write!(f, "CL"),
            Estado::Colima => write!(f, "CM"),
            Estado::Chiapas => write!(f, "CS"),
            Estado::Chihuahua => write!(f, "CH"),
            Estado::DistritoFederal => write!(f, "DF"),
            Estado::Cdmx => write!(f, "DF"),
            Estado::Durango => write!(f, "DG"),
            Estado::Guanajuato => write!(f, "GT"),
            Estado::Guerrero => write!(f, "GR"),
            Estado::Hidalgo => write!(f, "HG"),
            Estado::Jalisco => write!(f, "JC"),
            Estado::EstadoDeMexico => write!(f, "MC"),
            Estado::Extranjero => write!(f, "NE"),
            Estado::Michoacan => write!(f, "MN"),
            Estado::Morelos => write!(f, "MS"),
            Estado::Nayarit => write!(f, "NT"),
            Estado::NuevoLeon => write!(f, "NL"),
            Estado::Oaxaca => write!(f, "OC"),
            Estado::Puebla => write!(f, "PL"),
            Estado::Queretaro => write!(f, "QT"),
            Estado::QuintanaRoo => write!(f, "QR"),
            Estado::SanLuisPotosi => write!(f, "SP"),
            Estado::Sinaloa => write!(f, "SL"),
            Estado::Sonora => write!(f, "SR"),
            Estado::Tabasco => write!(f, "TC"),
            Estado::Tamaulipas => write!(f, "TS"),
            Estado::Tlaxcala => write!(f, "TL"),
            Estado::Veracruz => write!(f, "VZ"),
            Estado::Yucatan => write!(f, "YN"),
            Estado::Zacatecas => write!(f, "ZS"),
        }
    }
}
