use std::fmt;
pub enum MalasPalabras {
    Baca,
    Baka,
    Buei,
    Buey,
    Caca,
    Caco,
    Caga,
    Cago,
    Caka,
    Cako,
    Coge,
    Cogi,
    Coja,
    Coje,
    Coji,
    Cojo,
    Cola,
    Culo,
    Falo,
    Feto,
    Geta,
    Guei,
    Guey,
    Jeta,
    Joto,
    Kaca,
    Kaco,
    Kaga,
    Kago,
    Kaka,
    Kako,
    Koge,
    Kogi,
    Koja,
    Koje,
    Koji,
    Kojo,
    Kola,
    Kulo,
    Lilo,
    Loca,
    Loco,
    Loka,
    Loko,
    Mame,
    Mamo,
    Mear,
    Meas,
    Meon,
    Miar,
    Mion,
    Moco,
    Moko,
    Mula,
    Mulo,
    Naca,
    Naco,
    Peda,
    Pedo,
    Pene,
    Pipi,
    Pito,
    Popo,
    Puta,
    Puto,
    Qulo,
    Rata,
    Roba,
    Robe,
    Robo,
    Ruin,
    Seno,
    Teta,
    Vaca,
    Vaga,
    Vago,
    Vaka,
    Vuei,
    Vuey,
    Wuei,
    Wuey,
}

impl fmt::Display for MalasPalabras {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MalasPalabras::Baca => write!(f, "BXCA"),
            MalasPalabras::Baka => write!(f, "BXKA"),
            MalasPalabras::Buei => write!(f, "BXEI"),
            MalasPalabras::Buey => write!(f, "BXEY"),
            MalasPalabras::Caca => write!(f, "CXCA"),
            MalasPalabras::Caco => write!(f, "CXCO"),
            MalasPalabras::Caga => write!(f, "CXGA"),
            MalasPalabras::Cago => write!(f, "CXGO"),
            MalasPalabras::Caka => write!(f, "CXKA"),
            MalasPalabras::Cako => write!(f, "CXKO"),
            MalasPalabras::Coge => write!(f, "CXGE"),
            MalasPalabras::Cogi => write!(f, "CXGI"),
            MalasPalabras::Coja => write!(f, "CXJA"),
            MalasPalabras::Coje => write!(f, "CXJE"),
            MalasPalabras::Coji => write!(f, "CXJI"),
            MalasPalabras::Cojo => write!(f, "CXJO"),
            MalasPalabras::Cola => write!(f, "CXLA"),
            MalasPalabras::Culo => write!(f, "CXLO"),
            MalasPalabras::Falo => write!(f, "FXLO"),
            MalasPalabras::Feto => write!(f, "FXTO"),
            MalasPalabras::Geta => write!(f, "GXTA"),
            MalasPalabras::Guei => write!(f, "GXEI"),
            MalasPalabras::Guey => write!(f, "GXEY"),
            MalasPalabras::Jeta => write!(f, "JXTA"),
            MalasPalabras::Joto => write!(f, "JXTO"),
            MalasPalabras::Kaca => write!(f, "KXCA"),
            MalasPalabras::Kaco => write!(f, "KXCO"),
            MalasPalabras::Kaga => write!(f, "KXGA"),
            MalasPalabras::Kago => write!(f, "KXGO"),
            MalasPalabras::Kaka => write!(f, "KXKA"),
            MalasPalabras::Kako => write!(f, "KXKO"),
            MalasPalabras::Koge => write!(f, "KXGE"),
            MalasPalabras::Kogi => write!(f, "KXGI"),
            MalasPalabras::Koja => write!(f, "KXJA"),
            MalasPalabras::Koje => write!(f, "KXJE"),
            MalasPalabras::Koji => write!(f, "KXJI"),
            MalasPalabras::Kojo => write!(f, "KXJO"),
            MalasPalabras::Kola => write!(f, "KXLA"),
            MalasPalabras::Kulo => write!(f, "KXLO"),
            MalasPalabras::Lilo => write!(f, "LXLO"),
            MalasPalabras::Loca => write!(f, "LXCA"),
            MalasPalabras::Loco => write!(f, "LXCO"),
            MalasPalabras::Loka => write!(f, "LXKA"),
            MalasPalabras::Loko => write!(f, "LXKO"),
            MalasPalabras::Mame => write!(f, "MXME"),
            MalasPalabras::Mamo => write!(f, "MXMO"),
            MalasPalabras::Mear => write!(f, "MXAR"),
            MalasPalabras::Meas => write!(f, "MXAS"),
            MalasPalabras::Meon => write!(f, "MXON"),
            MalasPalabras::Miar => write!(f, "MXAR"),
            MalasPalabras::Mion => write!(f, "MXON"),
            MalasPalabras::Moco => write!(f, "MXCO"),
            MalasPalabras::Moko => write!(f, "MXKO"),
            MalasPalabras::Mula => write!(f, "MXLA"),
            MalasPalabras::Mulo => write!(f, "MXLO"),
            MalasPalabras::Naca => write!(f, "NXCA"),
            MalasPalabras::Naco => write!(f, "NXCO"),
            MalasPalabras::Peda => write!(f, "PXDA"),
            MalasPalabras::Pedo => write!(f, "PXDO"),
            MalasPalabras::Pene => write!(f, "PXNE"),
            MalasPalabras::Pipi => write!(f, "PXPI"),
            MalasPalabras::Pito => write!(f, "PXTO"),
            MalasPalabras::Popo => write!(f, "PXPO"),
            MalasPalabras::Puta => write!(f, "PXTA"),
            MalasPalabras::Puto => write!(f, "PXTO"),
            MalasPalabras::Qulo => write!(f, "QXLO"),
            MalasPalabras::Rata => write!(f, "RXTA"),
            MalasPalabras::Roba => write!(f, "RXBA"),
            MalasPalabras::Robe => write!(f, "RXBE"),
            MalasPalabras::Robo => write!(f, "RXBO"),
            MalasPalabras::Ruin => write!(f, "RXIN"),
            MalasPalabras::Seno => write!(f, "SXNO"),
            MalasPalabras::Teta => write!(f, "TXTA"),
            MalasPalabras::Vaca => write!(f, "VXCA"),
            MalasPalabras::Vaga => write!(f, "VXGA"),
            MalasPalabras::Vago => write!(f, "VXGO"),
            MalasPalabras::Vaka => write!(f, "VXKA"),
            MalasPalabras::Vuei => write!(f, "VXEI"),
            MalasPalabras::Vuey => write!(f, "VXEY"),
            MalasPalabras::Wuei => write!(f, "WXEI"),
            MalasPalabras::Wuey => write!(f, "WXEY"),
        }
    }
}
